openapi: 3.0.0
info:
  title: ChronoGamer API
  version: 1.0.0
  description: API para la gestión de usuarios y videojuegos con autenticación JWT
paths:
  /api/auth/register:
    post:
      summary: Registra un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: testuser
                password:
                  type: string
                  example: password123
      responses:
        201:
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  username:
                    type: string
        400:
          description: El nombre de usuario ya existe
        500:
          description: Error del servidor
  /api/auth/login:
    post:
      summary: Inicia sesión y obtiene un token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: testuser
                password:
                  type: string
                  example: password123
      responses:
        200:
          description: Token JWT generado
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: Credenciales inválidas
        500:
          description: Error del servidor
  /api/games:
    get:
      summary: Obtiene una lista de juegos desde IGDB
      parameters:
        - name: date
          in: query
          required: false
          description: Fecha de lanzamiento en formato YYYY-MM-DD. Por defecto, se utiliza la fecha actual.
          schema:
            type: string
      responses:
        200:
          description: Lista de juegos obtenida
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1234
                    name:
                      type: string
                      example: Chrono Trigger
                    release_date:
                      type: string
                      example: 1995-03-11
                    platforms:
                      type: array
                      items:
                        type: string
                        example: Super Nintendo
        500:
          description: Error del servidor
  /api/games/{id}:
    get:
      summary: Obtiene los detalles de un juego por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID del juego en la base de datos de IGDB
          schema:
            type: integer
            example: 1234
      responses:
        200:
          description: Detalles del juego obtenidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1234
                  name:
                    type: string
                    example: Chrono Trigger
                  description:
                    type: string
                    example: "Un juego de rol épico lanzado en 1995."
                  release_date:
                    type: string
                    example: 1995-03-11
                  genres:
                    type: array
                    items:
                      type: string
                      example: RPG
                  platforms:
                    type: array
                    items:
                      type: string
                      example: Super Nintendo
                  screenshots:
                    type: array
                    items:
                      type: string
                      example: "https://example.com/screenshot.jpg"
        404:
          description: Juego no encontrado
        500:
          description: Error del servidor
